### ISSUE TITLE
Documentation needs to be updated.

### ISSUE THREAD

**Issue by stai001c** [Comcast/drive-thru#3]
https://github.com/Comcast/drive-thru/blob/master/src/main/java/com/comcast/drivethru/test/MockEasyRestClient.java

Documentation on this page is referencing classes belonging to com.comcast.tvx.megahttp.\* Which looks like it is no longer using.

**Comment by trentontrees** [comment]
Just updated the documentation.

**Comment by stai001c** [comment]
Awesome. FYI, I found this doing a google search on com.comcast.tvx packages.
